version: "2.19"
services:
  aaa:
    container_name: aaa
    build: 
      context: "."
      dockerfile: "./docker/aaa/Dockerfile"
    ports: 
      - "5000:5000"
    depends_on: 
    - database
    - cache
    networks:
    - conn

  admin:
    container_name: admin
    build: 
      context: "."
      dockerfile: "./docker/admin/Dockerfile"
    ports: 
    - "5002:5002"
    depends_on: 
    - aaa
    - database
    - cache
    networks:
    - conn

  tms:
    container_name: tms
    build:
      context: "."
      dockerfile: "./docker/tms/Dockerfile"
    ports: 
    - "5001:5001"
    depends_on: 
    - admin
    - database
    - cache
    networks:
    - conn

  database:
    container_name: database
    build:
      context: "."
      dockerfile: "./docker/db/Dockerfile"
    environment:
      POSTGRES_DB: "tms_o"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1685"
    ports:
    - "5432:5432"
    networks:
    - conn
  
  cache:
    container_name: cache
    image: redis:7.2-rc-alpine
    ports:
    - "6379:6379"
    networks:
    - conn

networks:
  conn:
  # proxy:
  #   container_name: proxy
  #   build: "./proxy"
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - web
  #   volumes:
  #     - ./proxy:/app